import express from 'express';
import helmet from 'helmet';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {catalog} from './catalog.js';
import {createOrder,listOrders,getOrderByCode} from './db.js';
import {notifyOrder,notifyFeedback} from './notifications.js';
const dir=path.dirname(fileURLToPath(import.meta.url));
const app=express();
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:'100kb'}));
app.use(express.static(path.join(dir,'../public')));
app.get('/api/health',(q,r)=>r.json({ok:true,app:'MMW-ORDER'}));
app.get('/api/catalog',(q,r)=>r.json(catalog));
app.get('/api/orders',async(q,r)=>{try{const t=String(q.query.token||'');if(!/^[a-f0-9]{48}$/.test(t))return r.status(400).json({error:'Некорректный токен'});r.json({orders:await listOrders(t)})}catch(e){console.error(e);r.status(500).json({error:'Не удалось загрузить заявки.'})}});
app.post('/api/order-access',async(q,r)=>{try{const id=String(q.body?.orderId||'').trim(),code=String(q.body?.code||'').trim();const order=await getOrderByCode(id,code);if(!order)return r.status(404).json({error:'Заявка или код доступа не найдены.'});r.json({order})}catch(e){console.error(e);r.status(500).json({error:'Не удалось открыть заявку.'})}});
app.post('/api/orders',async(q,r)=>{try{const p=q.body||{};if(!p.customerName?.trim()||!p.phone?.trim()||!p.email?.trim()||!Array.isArray(p.items)||!p.items.length)return r.status(400).json({error:'Заполните имя, телефон, email и добавьте позицию.'});if(!/^\S+@\S+\.\S+$/.test(p.email))return r.status(400).json({error:'Проверьте email.'});const o=await createOrder({customerName:p.customerName.trim().slice(0,120),phone:p.phone.trim().slice(0,40),email:p.email.trim().slice(0,160),company:String(p.company||'').trim().slice(0,160),projectType:String(p.projectType||'').trim().slice(0,100),address:String(p.address||'').trim().slice(0,300),comment:String(p.comment||'').trim().slice(0,2000),items:p.items});const notifications=await notifyOrder(o);r.status(201).json({order:o,accessCode:o.accessCode,notifications})}catch(e){console.error(e);r.status(500).json({error:'Не удалось создать заявку.'})}});
app.post('/api/feedback',async(q,r)=>{try{const p=q.body||{};if(!p.name?.trim()||!p.contact?.trim()||!p.message?.trim())return r.status(400).json({error:'Заполните имя, контакт и сообщение.'});const result=await notifyFeedback({name:String(p.name).trim().slice(0,120),contact:String(p.contact).trim().slice(0,160),message:String(p.message).trim().slice(0,2000)});r.status(201).json({ok:true,notifications:result})}catch(e){console.error(e);r.status(500).json({error:'Не удалось отправить сообщение.'})}});
app.listen(process.env.PORT||3000,()=>console.log('MMW-ORDER listening'));
